# Generated by Django 4.2.3 on 2023-08-03 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('619e6f8c-f5e2-4026-a2d4-99be67237881'), primary_key=True, serialize=False),
        ),
    ]
