# Generated by Django 4.2.3 on 2023-10-12 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_marketer_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7c20ec6b-f9e7-4848-aade-ec1f83829c77'), primary_key=True, serialize=False),
        ),
    ]
